name: Build Debian Package

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup system
      run: |
        apt-get update && apt-get install --no-install-recommends -y \
        build-essential \
        debhelper-compat dh-dkms debhelper linux-headers-generic \
        device-tree-compiler \
        dpkg-dev \
        sudo \
        && rm -rf /var/lib/apt/lists/*


    - name: Build Debian Package
      run: |
        export VERSION=${GITHUB_REF#refs/tags/}
        bash ./createDebianPackage.sh
    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: ./*.deb
