name: Build Debian Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev debhelper

    - name: Build Debian Package
      run: |
        sudo rm -rf build
        mkdir -p build
        cp -r debian_package build/debian
        cp -r vc-mipi-driver-bcm2712 build/debian
        mkdir -p build/debian/tmp
        cp -r src build/
        cp dkms.conf build/
        cd build
        sudo dpkg-buildpackage -us -uc -b
    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: build/*.deb
        platforms: linux/arm64