name: Build Debian Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev debhelper

    - name: Build Debian Package
      run: |
        docker run --platform linux/arm64 -v ${PWD}:/workspace -w /workspace debian:booksworm dpkg-buildpackage bash .createDebianPackage.sh
    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: build/*.deb
